config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'monuments#index'

  get '/about', to: 'pages#about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :monuments, only: [:index, :show, :create, :new]
  resources :rentals, only: [:create, :show, :new, :index, :edit, :update]

  patch '/rentals/:id/approve', to: 'rentals#mark_as_approved', as: :accept
  patch '/rentals/:id/decline', to: 'rentals#mark_as_declined', as: :decline
  get '/rentals/:id', to: 'rentals#status'
  get '/dashboard', to: 'pages#dashboard'
end




# JOURNEY

# TO IMPLEMENT
# resources :reviews, only: [:create, :new, :show]

# TO DO:
# reviews

# monuments/:id/reviews/new POST  monuments create
# monuments/:id/reviews GET monuments show

# -----------------------------------------------

# DONE
# indexes:
# GET "/monuments"  GET monuments index ok
# users/:id/monuments GET monuments index ok

# shows:
# /monuments/:id  GET monuments show ok
# users/:id GET users show

# creates
# users/:id/monuments/new POST  monuments create ok
# users/new POST  users create ok

# rentals
# /users/:id/rentals show
# monuments/:id/rentals POST  rentals create
# monuments/:id/rentals/new GET rentals new
# users/:id/rentals GET rentals index
# users/:id/rentals/:id/confirm PATCH rentals update

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monument.rb
class Monument < ApplicationRecord

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :rentals
  has_many_attached :photos

  validates :name, presence: true
  validates :availability, presence: true
  validates :price, presence: true
  validates :description, presence: true
  # validates :coordinates, presence: true not needed as we have longitude and latitude now
  validates :longitude, presence: true
  validates :latitude, presence: true
  validates :description, length: { maximum: 450, too_long: "%{count} characters is the maximum allowed" }
  validates :price, numericality: { only_float: true }
  validates :photos, presence:true  
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :monument

  validates :date_of_delivery, presence: true
  validates :date_of_return, presence: true
  validates :monument_id, allow_blank: false, presence: true
  validates :user_id, allow_blank: false, presence: true
  
  def approve
    self.status = true
  end

  def decline
    self.status = false
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :rentals
  has_many :monuments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # so pundit is used in every controller
  include Pundit

  # Pundit: white-list approach.
  # after each action, we verify that we have the user has the authorization to
  # access the page except for index

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private
  # we skip pundit for pages of controller pages and for devise controller
  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/monuments_controller.rb
class MonumentsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "name @@ :query OR address @@ :query"
      @monuments = policy_scope(Monument).where(sql_query, query: "%#{params[:query]}%")
    else
      @monuments = policy_scope(Monument)
    end

    @markers = @monuments.geocoded.map do |monument|
      {
        lat: monument.latitude,
        lng: monument.longitude,
        info_window: render_to_string(partial: "info_window", locals: { monument: monument })
      }
    end
  end

  def new
    @monument = Monument.new
    authorize @monument
  end

  def create
    @monument = Monument.new(monument_params)
    @monument.user = current_user

    authorize @monument

    if @monument.save
      redirect_to @monument, notice: 'The monument  was successfully created'
    else
      render :new
    end
  end

  def show
    @monument = Monument.find(params[:id])
    authorize @monument

     @markers =
      [{
        lat: @monument.latitude,
        lng: @monument.longitude,
        info_window: render_to_string(partial: "info_window", locals: { monument: @monument })
      }]
  end

  private

  def monument_params
    params.require(:monument).permit(:name, :availability, :price, :description, :longitude, :latitude, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def about
  end

  def dashboard
    # owner
    # The monuments the owner owns
    @my_monuments = Monument.where(user: current_user)

    # current_user.id is what links monument and rentals together
    # the monuments that are currently being rented
    @monuments_i_rent = Monument.joins(:rentals).where(rentals: { user_id: current_user.id })

    # the renters monuments that are currently rented (for the renter)
    @my_rentals = Rental.where(user: current_user).order(id: :desc)

    # requests sent to the owner from the renter
    @rental_requests_received = Rental.joins(:monument).where(monuments: { user_id: current_user.id })

    @pending_rental_requests_received = @rental_requests_received.select { |rental| rental.status.nil? }
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  
  def index
    # so the rentals made by one user show when he goes to this page see policy
    # for the scope
    @rentals = policy_scope(Rental)
  end

  def show
    @rental = Rental.find(params[:id])
    authorize @rental
  end

  def new
    @rental = Rental.new
    authorize @rental
  end

  def create
    # take the instance rental as a new one and white list it
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    # take the instance monument that can only be found with :monument_id
    # @monument = Monument.find(params[:monument_id])

    # give the authorization to rental
    authorize @rental

    # need to link monument to rental
    # @rental.monument = @monument
    # need to link user to current user


    # when it saves go back to the monument#show
    if @rental.save
      redirect_to monument_path(@rental.monument), notice: 'Your booking request has been received'
    #or redo the form
    else
      render :new
    end
  end

  def mark_as_approved
    @rental = Rental.find(params[:id])
    authorize @rental
    @rental.approve
    @rental.save
    redirect_to dashboard_path
  end

  def mark_as_declined
    @rental = Rental.find(params[:id])
    authorize @rental
    @rental.decline
    @rental.save
    redirect_to dashboard_path
  end

  def status?
    @rental = Rental.find_by_id(params[:id])
    @rental.status
  end

  private

  def rental_params
    params.require(:rental).permit(:user_id, :monument_id, :date_of_delivery, :date_of_return)
  end

  def set_rental
    @rental = Rental.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAMon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <style>
    /*font-family: 'Architects Daughter', cursive;*//*font-family: 'Lato', sans-serif;*/
    @import url('https://fonts.googleapis.com/css2?family=Architects+Daughter&family=Lato&display=swap');
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/navbar' %>



    <p class="alert"><%= alert %></p>
    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/monuments/_info_window.html.erb
<h2><%= monument.name %></h2>
<% if monument.availability == true %>
<p><%= "available" %></p>
<% end %>

app/views/monuments/_info_window_show.html.erb
<h2><%= @monument.name %></h2>
<% if @monument.availability == true %>
<p><%= "available" %></p>
<% end %>

app/views/monuments/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/jbox/image/upload/v1632591341/image_a16zyr.png);">
  <div class="banner-text">
    <h1>RentAMon</h1>
    <p>Your <strong>monument</strong> shipped <strong>anywhere</strong> in the <strong>world</strong>!</p>
    <%# SEARCH BAR START %>
    <div class="search">
      <%= form_tag monuments_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          id: "search_form",
          class: "searchTerm",
          placeholder: "What are you looking for?"
          %>
        <%= button_tag type: "submit" do %>
          <i class="fa fa-search searchButton"></i>
        <% end %>
      <% end %>
    </div>
    <%# SEARCH BAR END%>
  </div>
</div>

<div class="container" style="text-align: center;">
  <h1>Monuments for Rent</h1>
  <div class="cards">
    <% @monuments.each do |monument|%>
      <div class="monument-card">
        <a href=<%= monument_path(monument) %> >
          <% monument.photos.each_with_index do |photo, i| %>
            <%= cl_image_tag photo.key if i < 1 %>
          <% end %>
          <div class="monument-infos">
            <h2><%= monument.name %></h2>
            <p>Price $<%= monument.price%>/Day</p>
            <p>Status: <%= monument.availability ? "Available" : "Not Available" %></p>
          </div>
        </a>
      </div>
    <% end %>
  </div>

  <div class="btn btn-secondary">
    <%= link_to "Add your Monument", new_monument_path(@monument)%>
  </div>

  <!-- map starts here -->
  <div id="map"
    style="width: 100%; height: 600px; border-radius: 8px; box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.2);"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <!-- map ends here -->
</div>

app/views/monuments/new.html.erb
<div class="container">
  <h1>Add A Monument</h1>

  <%= simple_form_for @monument do |f| %>
    <%= f.input :name, label: 'Name of monument', error: 'Name is mandatory, please specify' %>
    <%= f.input :description %>
    <%= f.input :price , label: 'Price (in $/Day)'%>
    <%= f.input :latitude , label: 'Latitude' %>
    <%= f.input :longitude , label: 'Longitude' %>
    <%= f.input :availability , as: :radio_buttons, error: "Monument must be available in order to post"%>
    <%= f.input :photos, label: "3 Pictures Minimum", as: :file, input_html: { multiple: true } %>

    <%= f.button :submit, class:"btn btn-primary" %>
  
   <p><%= link_to 'Home', root_path %></p>
  <% end %>
</div>

app/views/monuments/show.html.erb
<div class="container">
  <h1><%= @monument.name %></h1>
  <% if @monument.user != current_user %>
    <h2><%= "Available" if @monument.availability == true %></h2>
  <% end %>
  <p>Description: <%= @monument.description %></p>

  <div class="photos-container">
    <% @monument.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  </div>

  <div class="monument-info">
    <h3>Rent this monument for: $<%= @monument.price %>/day</h3>
    <%# <p>Coordinates: lat.@monument.latitude, long.<%= @monument.longitude</p> %>
  </div>

    <% if @monument.user != current_user %>
      <div class="btn btn-secondary">
        <%= link_to 'Book now', new_rental_path(@monument) %>
      </div>
    <% end %>

  <div id="map"
    style="width: 100%; height: 600px; border-radius: 8px; box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.2); margin-bottom: 12px; margin-top: 12px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

    <%= link_to "Back to Monuments List", monuments_path %>

</div>

app/views/pages/about.html.erb
<div class="container">
  <div class="about-container">
    <img src="https://res.cloudinary.com/jbox/image/upload/v1632597277/image_1_cxyyfl.png" alt="Atlas carrying the world" class="about-image">
    <div class="about-info">
      <h1>About us</h1>
      <p>Project Atlas, or Rentamon as you know it, began as an experiment.</p>

      <p>How amazing would it be to move the most reknown monuments in the world from one place to another?</p>

      <h2>Challenge accepted!</h2>
      <p>All we needed was UNESCO’s approval and country leaders to give the green light. After showing our great devotion and good care, the market increased like crazy -more than the founders could have actually imagined-.</p>

      <p>Rentamon’s collection started with small edifices. The catalogue grew bigger and bigger in size as would its monuments in dimensions.
      Now with a complete offer, rentAMon is the only company to offer diversity of cultures from anywhere in the world to your home.</p>

      <div class="slogan"><p>RentAMON</p><p>Your monument shipped anywhere in the world!</p></div>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<!-- http://localhost:3000/dashboard -->
<!-- define username -->
<div class="container">
  <div class="header">
    <h1>Hello <%= current_user.email %> </h1>
      <p>Welcome to your dashboard</p>
  </div>

  <div class="info">
    <div class="message">
      <h2><MESSAGES></MESSAGES></h2>
    </div>

    <div class="d-flex flexor">
      <div class="owner-section">
        <!-- OWNER -->
        <h2>Your monuments:</h2>
        <p>You are currently trusting us with</p>
        <p> <span><%= @my_monuments.count %></span> of your monuments in our catalogue.</p>
        <!-- if user is a owner and a user booked his monument -->
        <!-- if Booking_request.count > 1 requests
          else request-->

        <p> You have have <span><%=pluralize @pending_rental_requests_received.count, "request" %> pending:</span><p>

        <% @pending_rental_requests_received.each do |rental| %>
        <%= rental.monument.name %> for <%= rental.date_of_delivery %> to <%= rental.date_of_return %>

          <!-- button -->

          <div class="d-flex justify-content-center buttons">
          <!-- got to call the right .status? with those buttons -> should send the appropriate message to the user-->
          <%= link_to 'Approve', accept_path(rental), method: :patch, class: 'btn blue blue-btn', data: { confirm: "Confirm this request?" } %>
          <%= link_to 'Decline', decline_path(rental), method: :patch, method: :patch, class: 'btn red red-btn', data: { confirm: "Confirm this request?" }%>
          </div>
        <% end %>
      </div>
      <!-- If TRUE send confirmation to the USER that made the RENTAL from the SHOW or is it the User that made the form on CREATE from MONUMENT -->
      <!-- If FALSE send refusal -->
      <!-- RENTER -->
      <div class="renter-section">
        <h2>Your bookings:</h2>
        <!-- CONFIRMATION be like-->
        Those are the rentals you made a request for:
        <br>
        <br>
          <% @my_rentals[0..3].select do |f| %>
          <%= f.monument.name %> for <%=f.date_of_delivery %> to <%= f.date_of_return %>
            <% if f.status == nil  %>
              <p> Rental is pending </p>
              <% elsif f.status == true  %>
              <p> Rental is approved </p>
              <% else %>
              <p> Rental is declined </p>
              <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

  <h1>MONUMENTS PATHS</h1>
  <%= link_to 'Monuments index', monuments_path %>
  <br>
  <%= link_to 'form to create a new monument', new_monument_path(@monument) %>
  <br>
  <br>
  <h1>Home page</h1>
  <%= link_to 'home page', root_path %>
  <br>
  <br>
<h2>Links to different pages to test - Can copy/paste tags </h2>
<ul>
  <h1>USER PATHS</h1>
  <%= link_to 'new_user_session -> Devise/sessions#new', new_user_session_path(@user) %>
  <br>
  <%= link_to 'user_session -> Devise/sessions#create', user_session_path(@user) %>
  <br>
  <%# <%= link_to 'destroy_user_session -> Devise/sessions#destroy (DOESNT WORK - ActiveRecord::RecordNotFound in UsersController#show) ', destroy_user_session_path(@user) %> %>
  <br>
  <%# <%= link_to 'new_user -> users#new (DOESNT WORK - Pundit::AuthorizationNotPerformedError in UsersController#new)', new_user_path(@user) %>
  <p>         users POST   /users(.:format)                                                                         users#create
  <p>           user GET    /users/:id(.:format)                                                                     users#show
  <h1>User Password/Registrations</h1>
  <%= link_to 'new_user_password -> devise/passwords#new', new_user_password_path(current_user) %>
  <br>
  <%= link_to 'edit_user_password -> devise/passwords#edit', edit_user_password_path(current_user) %>
  <br>
  <%= link_to 'user_password -> devise/passwords#update (DOESNT WORK - ActiveRecord::RecordNotFound in UsersController#show)', user_password_path(@user) %>
  <br>
  <p>           user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
  <p>                         PUT    /users/password(.:format)                                                                devise/passwords#update
  <p>                         POST   /users/password(.:format)                                                                devise/passwords#create
  <br>
  <%= link_to 'cancel_user_registration -> devise/registrations#cancel', cancel_user_registration_path(@user) %>
  <br>
  <%= link_to 'new_user_registration -> devise/registrations#new', new_user_registration_path(@user) %>
  <br>
  <%= link_to 'edit_user_registration -> devise/registrations#edit', edit_user_registration_path(@user) %>
  <br>
  <%= link_to 'user_registration -> devise/registrations#update (DOESNT WORK PROPERLY, ROUTING TO BE FIXED', user_registration_path(@user) %>
  <br>
  <p> PUT    /users(.:format)                                                                         devise/registrations#update
  <p> DELETE /users(.:format)                                                                         devise/registrations#destroy
  <p> POST   /users(.:format)                                                                         devise/registrations#create



  <h1>RENTALS PATHS (Need controller/views)</h1>
  <p> link_to 'rentals -> rentals#index', rentals_path </p>
  <p> link_to 'rental -> rentals#show', rental_path(@rental) %> </p>
  <p> link_to 'new_rental -> rentals#new', new_rental_path(@rental) </p>
  <p> link_to 'edit_rental -> rentals#edit', edit_rental_path(@rental) </p>
  <p> POST   /rentals(.:format)                                                                       rentals#create </p>
  <p> PATCH  /rentals/:id(.:format)                                                                   rentals#update </p>
  <p> PUT    /rentals/:id(.:format)                                                                   rentals#update </p>

  <h1>others...</h1>
  <p> user_monuments GET    /users/:user_id/monuments(.:format)                                                      monuments#index
  <p> user_monument GET    /users/:user_id/monuments/:id(.:format)                                                  monuments#show
</ul>

app/views/rental/new.html.erb
<h1>hello</h1>
<%= simple_form_for ([@monument, @rental]) do |f| %>
<%= f.input :name %>
<%= f.input :date_of_delivery%>
<%= f.input :date_of_return%>
<%= f.submit, "Book now"%>

<% end %>

app/views/rentals/new.html.erb
<div class="container">

  <h1>Booking the monument</h1>


<%= simple_form_for ([@monument, @rental]) do |f| %>
  <%= f.association :monument, as: :select %>
  <%= f.input :date_of_delivery, html5: true %>
  <%= f.input :date_of_return, html5: true  %>
  <%= f.submit "Confirm" %>
<% end %>
<%= link_to "Cancel", monuments_path %>
</div>

app/views/shared/_footer.html.erb
<div class="footer footer-logo">
  <div class="footer-header">
    <div class="footer-title">RentAMon</div>
    <div class="footer-description">Your monument shipped anywhere in the world!</div>
  </div>

  <div class="footer-body">
    <p>Created with ❤️ in MTL.</p>
    <%= link_to "About RentAMon", about_path %>
    <%= link_to "About Us", monuments_path %>
  </div>

  <div class="footer-copyright">
    <p>© 2021 RentAMon, Inc.</p>
    <div class="social-links">
      <a href="https://www.facebook.com"><i class="fab fa-facebook-f"></i></a>
      <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
      <a href="https://www.github.com"><i class="fab fa-github"></i></a>
      <a href="https://www.linkedin.com/"><i class="fab fa-linkedin-in"></i></a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/about">
    <img src="https://res.cloudinary.com/jbox/image/upload/v1632582060/production/rentamon_logo_red_no_bckground_sxn2lc.png" />
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<p class="notice"><%= notice %></p>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item"><%= link_to "Home", root_path %></li>
      <li class="nav-item"><%= link_to "Dashboard", dashboard_path %></li>
    <!-- identify the current user -->
      <% if user_signed_in? %>
      <li class="nav-item active">
        <span class="nav-link"><%= current_user.email%></span>
      </li>
      <% end %>
    <!-- identify the current user -->
      <!-- <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </li>
    </ul> -->
  </div>

 <!-- start for hamburger -->
  <div id="menu-bar">
 <!--  -->
    <div id="menu" onclick="onClickMenu()">
      <div id="bar1" class="bar"></div>
      <div id="bar2" class="bar"></div>
      <div id="bar3" class="bar"></div>
    </div>
  <!--  -->
  </div>
  </div>

  <div class="nav hamburger-container" id="nav">
    <ul>
      <div><li><%= link_to "My Bookings", dashboard_path %></li></div>
      <div><li><%= link_to "My Monuments", monuments_path %></li></div>
      <div><li><%= link_to "RentAMon Catalogue ", monuments_path %></li></div>
    </ul>
  </div>
  <!--  -->
  <!-- end for hamburger -->


<script>






</script>

app/views/users/new.html.erb
<div class="container">
  <%= simple_form_for @user do |f| %>
    <%= f.input :email %>
    <%= f.button :submit %>
  <% end %>
</div>